PARKING_FULL_MESSAGE = "Sorry, parking lot is full"
PARKING_CREATED_MESSAGE = "Created a parking lot with %{slot} slots"
PARKING_ALLOCATED_MESSAGE = "Allocated slot number: %{slot}"
PARKING_LEAVE_SLOT_MESSAGE = "Slot number %{slot} is free"
INVALID_SLOT_MESSAGE = "Slot Number is invalid"